# Generated by Django 4.0 on 2021-12-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prev_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
