# Generated by Django 4.0 on 2021-12-29 11:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_item_prev_quantity_csvfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='csvfiles',
            name='file',
            field=models.FileField(upload_to='files', validators=[users.models.validate_type_size]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=0, validators=[users.models.validate_value]),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, validators=[users.models.validate_value]),
        ),
    ]
