# Generated by Django 4.0 on 2021-12-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_transaction_options_alter_csvfiles_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField()),
                ('mac', models.IntegerField()),
                ('android', models.IntegerField()),
                ('ios', models.IntegerField()),
                ('others', models.IntegerField()),
            ],
        ),
    ]
