# Generated by Django 4.0 on 2021-12-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
